repository: dynamsoft-docs/document-viewer-docs
repositoryUrl: https://github.com/dynamsoft-docs/document-viewer-docs/blob/main
docFullPath: https://www.dynamsoft.com/document-viewer/docs
firstLevelUrl: /document-viewer/docs
docHomePage: /document-viewer/docs/introduction/
searchIndexName: Crawler-DDV-Docs

introduction: /document-viewer/docs/introduction/
gettingstarted: /document-viewer/docs/gettingstarted/
features: /document-viewer/docs/features/
viewer: /document-viewer/docs/viewer/
ui: /document-viewer/docs/ui/
api: /document-viewer/docs/api/
license: /document-viewer/docs/license/
releasenotes: /document-viewer/docs/releasenotes/
faq: /document-viewer/docs/faq/

useVersionTree: true

assets: /document-viewer/docs/assets/
edit_icon: /document-viewer/docs/assets/img-icon/edit-icon.png
smile_icon: /document-viewer/docs/assets/img-icon/icon-smile.png
sad_icon: /document-viewer/docs/assets/img-icon/icon-sad.png

baseurl: "/document-viewer/docs"

download: "/document-viewer/downloads/1000031-confirmation/"

plugins:
  - jemoji
  - jekyll-sitemap
  
relative_links:
  enabled:     true
  collections: true

collections:
  old:
    output: true
    permalink: /:path:output_ext
  v1.1:
    output: true
    permalink: /:path-:collection:output_ext
  v2.1:
    output: true
    permalink: /:path-:collection:output_ext
    
defaults:
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true
  - scope:
      path: "Hide_Tree_Page.html"
    values:
      sitemap: false

url: "https://www.dynamsoft.com" # sitemap root
